### ISSUE TITLE
cannot handle concurrent requests when running as a flask web app

### ISSUE THREAD

**Issue by keighrim** [clamsproject/app-whisper-wrapper#22]
### Bug Description

While an instance of this app is running as a flask web app, I can't send two or more request simultaneously. Namely, sending an additional request while a request is already being processed will "crash" the existing running process. 

### Reproduction steps

1. run `app.py`, keep the flask server in the foreground to see logs
2. open a new terminal and send a valid "source" MMIF to the server via `curl`, keep it running
3. open a new terminal and send another valid "source" MMIF (the source media file can be the same or different) to the server via `curl`

watch the first `curl` call immediately crashes on the server side and a 500 response is returned, with this error message: 
```
RuntimeError: The size of tensor a (232) must match the size of tensor b (227) at non-singleton dimension 3
```

### Expected behavior

Both `curl` calls are concurrently processed and 200 responses are returned for each.

### Additional context

Confirmed on both a native instance and a containerized instance. Also confirmed on CUDA mode and on CPU mode. 

If the second call uses a different `modelSize`, the error no longer occurs. (e.g., first with the default (tiny), second with `?modelSize=base`) .

**Comment by 1192119703jzx** [comment]
The issue is caused by the implementation of self.whisper_models. By caching the loaded model in self.whisper_models and reusing the model in the future, this implementation saves the loading time. However, this implementation also causes the reported issue: when the loaded model is being used by one request, calling this model from self.whisper_models and trying to use it by another request would crash the former request. My implementation in PR #23 solves this problem by adding self.model_usage = {}, which can keep the usage of each size of model. If the loaded model is being used, the new request will load a new model. If the loaded model is available, the new request will use the loaded model from self.whisper_models to save more time. In a test, two requests using the same model and audio are sent simultaneously. Both requests are processed successfully with the running times 0:01:57.619907 and 0:01:55.017295. Later, a new request using the same model and audio is sent and processed with sunning time 0:01:10.885199. This shows that the new implementation can handle two or more requests simultaneously and also keep the cached function.
